### PR TITLE
TRAFODION-2905 query id contain null

### PR DESCRIPTION
**Pull request by mashengchen**
if stmtLabel is "null" string, then it will skip driver's conditional judgment (if (stmtName ==null) throw exception).

### CODE REVIEW

**Comment by selvaganesang** [comment]
What makes the stmtLabel to be "null" string and why?

**Comment by mashengchen** [comment]
jenkins, retest

**Comment by mashengchen** [comment]
see DatabaseQuery.java Line228.  prepareCallStmt(null)
when the query's sessionAutoPrepare is false , there will pass null as param.

**Comment by selvaganesang** [comment]
Requesting @hegdean to take a look at why Trafci doesn't take care of  null stmtName

**Comment by mashengchen** [comment]
Can someone else review or merge this PR?

**Pull request merged**
