### PR TITLE
[Trafodion-2841] Windows ODBC supports building on vs2015

### PR DESCRIPTION
**Pull request by SuJinpei**
Add some vs2015 project files to support vs2015 and change original project files back to support vs2013.

### CODE REVIEW

**Comment by xwq** [comment]
If it need to support VS2015 , we can't update the vcxproj directly. You can add new project setting files for VS2015. 

It's better to add some different project files and let the developer to choose what VS version they want.

**Comment by SuJinpei** [comment]
Jenkins retest

**Comment by SuJinpei** [comment]
@xwq In the pull request of https://github.com/apache/trafodion/pull/1300, original vcproj files were unintended upgraded to vs2015 version.  So this pull request makes the original vcproj files back to support vs2013 and add .vs2015.vcproj files to support vs2015 to convenient different developers.

**Comment by SuJinpei** [comment]
Jenkins retest

**Comment by traflm** [comment]
@SuJinpei do you still work on this PR?

**Comment by SuJinpei** [comment]
@traflm Yes

**Comment by SuJinpei** [comment]
Jenkins retest

**Comment by SuJinpei** [comment]
I found the test failed caused by license issue of the vs2015 project file. But original vs2013 project file didn't contain license declaration too. Could anyone help me?

**Pull request closed without merging**
