### PR TITLE
[TRAFODION-2805] Add "or edition" to error info 4222

### PR DESCRIPTION
**Pull request by sumory**

### CODE REVIEW

**Comment by svarnau** [comment]
Rather than a new pull request, the title of PR#1297 should be edited.  Please close this one and modify the existing one.

**Comment by traflm** [comment]
I saw @DaveBirdsall 's comments in another, PR, so this is good.
I will merge this asap.

**Comment by traflm** [comment]
I saw @DaveBirdsall 's comments in another, PR, so this is good.
I will merge this asap.

**Comment by traflm** [comment]
sorry... I agree with @svarnau , so let's keep aligned, please close this one and modify the previous one.

**Pull request merged**
