### PR TITLE
[TRAFODION-2985] Revert 2.2.0 download links to mirror pointers

### PR DESCRIPTION
**Pull request by svarnau**

### CODE REVIEW

**Comment by svarnau** [comment]
The policy is a bit more complicated.  The checksum files should be on dist, so that the main files on the mirrors can be verified.  But only the most recent release should be on the mirrors. The older releases should be on the archive site.

**Comment by PierreSmits** [comment]
We can suffice with using the following for the download location:
https://www.apache.org/dyn/closer.lua/trafodion

This makes it future proof as it does not point to a specific release. The selected mirror will show the correct version..

**Comment by traflm** [comment]
+1
Just understand all these rules.

**Comment by gstein** [comment]
http://www.apache.org/legal/release-policy.html#host-GA

**Comment by DaveBirdsall** [comment]
Thanks for the policy pointer, Greg.

**Pull request merged**
