### PR TITLE
TRAFODION-2861

### PR DESCRIPTION
**Pull request by PierreSmits**
Removal of incubator references

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by zellerh** [comment]
+1

Looks good to me. However, there are many more files that refer to "incubator". Here is a list I got from this command:

```
find . -type f -exec grep -q incubator {} \; -print
```

```
DISCLAIMER
README
README.md
core/conn/jdbcT4/pom.xml
core/sqf/sql/scripts/install_apache_hadoop
core/sql/exp/exp_conv.cpp
core/sql/regress/fullstack2/EXPECTED062
core/sql/regress/fullstack2/EXPECTED062.RELEASE
core/sql/regress/privs2/EXPECTED140
core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/EXPECTED103
core/sql/regress/udr/EXPECTED108
core/trafodion.spec
doap.rdf
docs/client_install/pom.xml
docs/client_install/src/asciidoc/_chapters/introduction.adoc
docs/client_install/src/asciidoc/_chapters/jdbct4.adoc
docs/client_install/src/asciidoc/_chapters/sample_prog.adoc
docs/command_interface/pom.xml
docs/cqd_reference/pom.xml
docs/jdbct4ref_guide/pom.xml
docs/load_transform/pom.xml
docs/lob_guide/pom.xml
docs/lob_guide/src/asciidoc/_chapters/about.adoc
docs/lob_guide/src/asciidoc/_chapters/working_with_lob.adoc
docs/messages_guide/pom.xml
docs/odb_user/pom.xml
docs/provisioning_guide/pom.xml
docs/provisioning_guide/src/asciidoc/_chapters/about.adoc
docs/provisioning_guide/src/asciidoc/_chapters/enable_security.adoc
docs/provisioning_guide/src/asciidoc/_chapters/quickstart.adoc
docs/spj_guide/pom.xml
docs/spj_guide/src/asciidoc/_chapters/deploy_spjs.adoc
docs/spj_guide/src/resources/source/Inventory.java
docs/spj_guide/src/resources/source/Payroll.java
docs/spj_guide/src/resources/source/Sales.java
docs/spj_guide/src/resources/source/adjustSalary.java
docs/spj_guide/src/resources/source/employeeJob.java
docs/spj_guide/src/resources/source/lowerPrice.java
docs/spj_guide/src/resources/source/numDailyOrders.java
docs/spj_guide/src/resources/source/numMonthlyOrders.java
docs/spj_guide/src/resources/source/orderSummary.java
docs/spj_guide/src/resources/source/partData.java
docs/spj_guide/src/resources/source/partLocations.java
docs/spj_guide/src/resources/source/projectTeam.java
docs/spj_guide/src/resources/source/supplierInfo.java
docs/spj_guide/src/resources/source/supplyQuantities.java
docs/spj_guide/src/resources/source/topSalesReps.java
docs/spj_guide/src/resources/source/totalPrice.java
docs/sql_reference/pom.xml
docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc
docs/src/site/markdown/download.md
docs/src/site/markdown/enable-secure-trafodion.md
docs/src/site/markdown/index.md
docs/src/site/markdown/ldapcheck.md
docs/src/site/markdown/ldapconfigcheck.md
docs/src/site/markdown/quickstart.md
docs/src/site/site.xml
install/ambari-installer/traf_ambari.spec
licenses/lic-server-src
licenses/lic-test-src
pom.xml
tools/docker/Dockerfile
tools/docker/start-compile-docker.sh
```

**Comment by traflm** [comment]
Thanks Pierre, but this is duplicated with https://github.com/apache/trafodion/pull/1359
I think #1359 is more complete changes.

**Comment by DaveBirdsall** [comment]
Hi @PierreSmits: I committed @svarnau's pull request #1359 just now; if you merge that into your workspace you can see what changes have already been done, and can better tell what more must be done. Thanks.

**Comment by PierreSmits** [comment]
Should we continue to show this PR, when it has been superseded by newer?

**Comment by DaveBirdsall** [comment]
No. I think you did the right thing by closing this PR just now.

**Pull request closed without merging**
