### PR TITLE
[TRAFODION-2943]

### PR DESCRIPTION
**Pull request by sbroeder**
Fix to add # at the beginning of the script to enable bash

### CODE REVIEW

**Comment by svarnau** [comment]
Looks like PR1432 makes the same change.

**Comment by sureshsubbiah** [comment]
I merged PR 1432 in. I suppose we should suggest that devs assign a JIRA to themselves as they start working on it. I am sorry @sbroeder that we did not merge this PR. Thank you.

**Comment by DaveBirdsall** [comment]
@sbroeder, do you want to close this pull request since the problem is already fixed?

**Comment by sbroeder** [comment]
Yes, sorry, I thought Suresh had closed it when the other pull request was merged.


________________________________

**Pull request closed without merging**
