### PR TITLE
[TRAFODION-2861] Backport to release2.2 branch

### PR DESCRIPTION
**Pull request by svarnau**
This includes doc changes for 2.2 docs to be generated without incubating references. (Main website is generated from master branch.)

Also includes packaging changes to remove incubating. 2.2.0 will be first TLP release.

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, retest

**Comment by traflm** [comment]
I will merge this asap

**Comment by traflm** [comment]
sorry, I failed to merge this, not sure what going wrong, @DaveBirdsall 、 @saruna could you help here? 
Here is my commands, but it doesn't merge this PR into Release 2.2 branch:

 1018  git clone https://github.com/apache/trafodion
 1019  cd trafodion/
 1020  git remote add apache https://liuming@git-wip-us.apache.org/repos/asf/trafodion.git
 1021  git fetch apache
 1022  git checkout -b mrg_1393 apache/release2.2
 1023  git fetch origin +refs/pull/1393/head
 1024  git merge --no-ff -m "[TRAFODION-2861] Backport to release2.2 branch" FETCH_HEAD
 1025  git log apache/master..HEAD
 1026  git diff apache/master HEAD
 1027  git log apache/master..HEAD
 1028  git branch -a
 1029  git remote -v
 1030  git push apache origin/release2.2

Not sure which step is wrong

**Comment by DaveBirdsall** [comment]
Hi @traflm. You don't include any output so I'm not sure what's failing.

In your git log and git diff steps, you need to say apache/release2.2 instead of apache/master. So your git log and git diff commands were likely showing a lot more stuff than you expected.

The git push command should be "git push apache HEAD:release2.2

@svarnau, do you see any other issues?

**Comment by svarnau** [comment]
Yes, commands 1025,1026 are comparing to master branch. They should be comparing release2.2 branch. But as Dave says, it is command 1030 that is wrong. Dave has the right syntax to push HEAD to release2.2 branch.

**Comment by traflm** [comment]
thank you both! 
Let me try it again by using correct 1030 command

**Pull request merged**
