### PR TITLE
[TRAFODION-3236] allocate revcive buffer by using dynamic array sizing instead of allocate from heap dynamically

### PR DESCRIPTION
**Pull request by Guo-Heng**

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Not sure why the regression tests are failing. The symptom is very weird. On the chance that it is environmental, I'll rerun the tests.

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
The regression tests failed again with similar results. @Guo-Heng, could you run the checktest2 suite in your environment and see if it also fails for you?

**Comment by Guo-Heng** [comment]
I discussed it with a few colleagues including Kenny. The result of the discussion is that we agree that the chances of a buffer being too long are very small, so we don't have to do this.

**Pull request closed without merging**
