### PR TITLE
Add "or edition" to error info 4222

### PR DESCRIPTION
**Pull request by sumory**

### CODE REVIEW

**Comment by svarnau** [comment]
Please reference a JIRA to explain purpose of this change.  Preferably add to PR title in [brackets] so that github comments are updated to jita.
Thanks.

**Comment by svarnau** [comment]
jenkins, ok to test

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by selvaganesang** [comment]
Ditto the comments made by @svarnau

**Comment by traflm** [comment]
@sumory could you close this PR? Since you have a new one. Thanks .

**Comment by traflm** [comment]
@sumory please update this PR. The title should contain the JIRA ID, and please make sure the test pass.

**Pull request closed without merging**
